spring.application.name=oci-doc-assistant
spring.kafka.bootstrap-servers=localhost:9092
spring.elasticsearch.uris=http://localhost:9200
server.port=8080
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB